### ISSUE TITLE
v2.0.0 not updated in npm

### ISSUE THREAD

**Issue by wlingke** [creeperyang/koa-xml-body#4]
I tried to install `@2` and got invalid

**Comment by creeperyang** [comment]
I publish `v2.0.0` with tag `next`. So you can install with:

```bash
npm install koa-xml-body@next
npm install koa-xml-body@2
```

**Comment by creeperyang** [comment]
@wlingke I add `v2.0.0` to `latest` tag just now. And I think you will have no trouble about installing now.

Let me know if you still suffer it.

**Comment by wlingke** [comment]
Works great now! thanks :)
