### ISSUE TITLE
【优化】与koa-body冲突

### ISSUE THREAD

**Issue by hhhuaang** [creeperyang/koa-xml-body#8]
kao-xml-body 与 koa-body 一起使用的时候，koa-body会为xml格式的数据添加空对象，造成后面的koa-xml不工作，如果把koa-xml-body放在 koa-body前面，koa-body会用一个空对象覆盖koa-xml-body添加到ctx.request.body 上的数据。

**Comment by hhhuaang** [comment]
我在本地修改了代码，
![image](https://user-images.githubusercontent.com/10963105/61762531-d8af9a80-ae04-11e9-8091-0de84fb6a08e.png)
但是无法把代码push到您的repo。

**Comment by creeperyang** [comment]
你可以用 `key` 来指定 `koa-xml-body` 使用 `ctx.request["the-key-you-specified"]`来处理和存储数据，防止冲突和被覆盖。

文档：<https://github.com/creeperyang/koa-xml-body#options>
